language: cpp

git:
  depth: false

sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - BUILD_NAME=GCC-6
        - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - BUILD_NAME=GCC-7
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"
    - os: osx
      osx_image: xcode9.2
      env:
        - BUILD_NAME=OSX-Clang
        - MATRIX_EVAL="export CC=clang && export CXX=clang++"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - BUILD_NAME=Clang-5
        - MATRIX_EVAL="export CC=clang-5.0 && export CXX=clang++-5.0 && sudo apt-get remove gcc g++"
  allow_failures:
    - env: BUILD_NAME=GCC-6
    - env: BUILD_NAME=OSX-GCC
    - env: BUILD_NAME=Clang-5

before_install:
  - eval "${MATRIX_EVAL}" 
  - $CC --version
  - $CXX --version

install:
  - ./gradlew --console=plain

script:
  - ./gradlew --console=plain assemble
  - ./gradlew --console=plain check

after_failure:
  - shopt -s nullglob
  - tail -n+1 {.,lib}/build/tmp/*{Library,Executable,GoogleTestExe}*/*.txt 

